version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres-container
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres-volume:/var/lib/postgresql
    restart: on-failure
    networks:
      - moipok-network

volumes:
  postgres-volume:

networks:
  moipok-network:
    driver: bridge